### ISSUE TITLE
Scenario 6:  Set discussion topic committee: add committee to a discussion topic / Scenario 6.1:  Edit Committee / Scenario 6.2:  remove Committee 

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#10]
**Scenario 6:  Set Discussion topic committee: add committee to a discussion topic**

**Entry point:**  Topic management button from admin channel, select topic from drop down list,  manage committees button and add committee button

**User Story**
As an admin
I want to set the committee for a proposal topic
So that proposals can be  reviewed by the appropriate group of reviewers

**Acceptance criteria**
OK
Given a valid discussion topic name, Reviewers group and number of members selected from the list
When the Manage committee  button is executed
Then the add committee button is activated, by clicking on it, It will present a modal to add the reviewers group (should have a drop list with all the groups names), submitting the name of the group will add them as committee to the topic

KO
Given an invalid group name written in the modal
When the Submit button is executed
Then the system returns an error message indicating the issue

- 

**Scenario 6.1:  Edit Committee** 

**Entry point:** Topic management button from admin channel, select topic from drop down list, manage committees button and Edit XX group 

**User Story**
As an admin
I want to edit the committee of a proposal topic
So that proposals can be reviewed by the appropriate group of reviewers

**Acceptance criteria**
OK
Given a valid committee added to the topic
When the Edit XX group  button is executed
Then it will present a modal to edit the committee’s number of members, submitting the number of members will update the committee

KO
not considered so far

-

**Scenario 6.2: Remove Committee** 

**Entry point:** Topic management button from admin channel, select topic from drop down list, manage committees button and Remove XX group

**User Story**
As an admin
I want to remove the committee of a proposal topic
So that proposals can be reviewed by the appropriate group of reviewers

**Acceptance criteria**
OK
Given a valid  Reviewers group added to the topic
When the Remove XX group  button is executed
Then it will present a confirmation message to remove the committee from the topic, a confirmation message will be shown and by clicking on confirm remove button the committee will be removed

KO
not considered so far

-
**User type:** Admin / Admin discord channel

**Comment by remigiusz-antczak** [comment]
Scenario 6: Set proposal topic committee: add committee to a topic

I created a new committee for a topic called "topic1" from a group called "reviewers-group" and received a correct indication that the committee was created:
<img width="411" alt="image" src="https://github.com/user-attachments/assets/360f9a56-1947-421f-879e-73026d804d62">

Then, I tried to add another committee for the same topic and from the same group and received a correct response:
`Error adding committee: A committee for this SME group already exists for this topic`

<img width="786" alt="image" src="https://github.com/user-attachments/assets/ef751df7-42a9-4682-a3db-7975284f983e">

Then, I tried to add another committee for the same topic but from a group that doesn't exist and received a correct response:
` Error adding committee: SME Group not found`

<img width="524" alt="image" src="https://github.com/user-attachments/assets/84644ea7-9848-442c-bd78-9b27b2507999">

Proof:

https://github.com/user-attachments/assets/90bd74cc-6051-4148-bce9-5c10af2f1fca


Comments:
1. The modal mentioned in the acceptance criteria (`Then the add committee button is activated, by clicking on it, It will present a modal to add the reviewers group (should have a drop list with all the groups names), submitting the name of the group will add them as committee to the topic`) should have a drop-down list with available groups; currently, it doesn't offer that functionality. Please review if it's something simple to improve.
2. After successfully creating a new committee, there's no success message, which might confuse people since in the other sections (from previous testing scenarios) there are notification messages after executing any action. Please review if it could be improved here. 
3. Please consider unifying notification and error messages here, too, as in the previous scenarios


Scenario 6.1: Edit Committee

I successfully changed the number of members of a committee.

Proof:


https://github.com/user-attachments/assets/12338757-4193-425c-ad14-8becfc659cb6


Comments:
1. After successfully editing the number of members in a committee, there's no success message, which might confuse people since in the other sections (from previous testing scenarios) there are notification messages after executing any action. Please review if it could be improved here. 


Scenario 6.2: Remove Committee

I successfully removed a committee from a topic (canceling removal button works correctly, too).

Proof:


https://github.com/user-attachments/assets/a4dc3bc5-15cf-4b98-a5c2-e8997a7e3819


Comments:
1. After successfully removing a committee, there's no success message, which might confuse people since, in the other sections (from previous testing scenarios), there are notification messages after executing any action. Please review if it could be improved here.

**Comment by iluxonchik** [comment]
> The modal mentioned in the acceptance criteria (Then the add committee button is activated, by clicking on it, It will present a modal to add the reviewers group (should have a drop list with all the groups names), submitting the name of the group will add them as committee to the topic) should have a drop-down list with available groups; currently, it doesn't offer that functionality. Please review if it's something simple to improve.

I don't fully understand this one. Currently, you can set the committee members under "Funding Round Management" --> "Add Committee Members". Then, select the Funding Round, and you can add committee members to it. Then, it will update you on whether you've filled the required committee.

<img width="677" alt="6-1" src="https://github.com/user-attachments/assets/5c404948-06f2-40ad-bebc-d56ae342bc5f">

**Comment by remigiusz-antczak** [comment]
@iluxonchik this issue/scenario is about a different functionality - adding, editing, and removing committee within a topic

<img width="632" alt="image" src="https://github.com/user-attachments/assets/9af07f50-ea4c-4780-bd64-2b974258e630">

Then, from my understanding, this part about the pop-up modal with a drop-down menu to select the SME/Reviewer group name:
`Then the add committee button is activated, by clicking on it, It will present a modal to add the reviewers group (should have a drop list with all the groups names), submitting the name of the group will add them as committee to the topic`

Is about this one:

<img width="453" alt="image" src="https://github.com/user-attachments/assets/7ca355f8-61c7-4f26-8b46-24770f54a63e">

It would be great to have a drop-down menu to select from available SME/Reviewer groups instead of manually typing the group's name. 

Edit: I just saw your message in some other place that Discord doesn't allow drop-downs in the pop-up modals, so whatever we can do to improve user experience here is greatly appreciated!

**Comment by CristinaEche** [comment]
@iluxonchik 

As you mention we cannot have here a drop down list, but can we have an autofill option? we have that for the SurveyBot. That will help to retrieve the correct names.

Also we are missing a place where we can see the list of discussion topics, the list of committees added to a topic and the list of reviewers groups.
