### ISSUE TITLE
Scenario 9:  Create funding round: set round duration, set consideration phase, set deliberation phase, set voting phase / Scenario 9.1: Edit voting round  / Scenario 9.2: Remove funding round 

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#13]
**Entry points:** 
1. Admin channel , create new funding round button
2. Funding round channel, create new funding round button

**User story**
As an Admin
I want to create a funding round
So that it can be reviewed and activated for funding proposals.

**Warning** user must complete data of all the buttons:
If you don't set the round duration and the phases and dismiss the message, you have to start the voting round from scratch.

**Acceptance criteria:**
OK
Given a valid funding round topic
When I execute the create new funding round button, a drop down list is activated to select the round
Then the funding round modal details can be submitted

> **Modal details:**
> Funding round name
> Description
> Budget
> Voting Address-- **what is a valid voting address, a mina wallet?**
> Voting Open Until 

**And then** set round duration, set consideration phase, set deliberation phase, set voting phase buttons are activated, and all the data must be completed. Once the data of each option/button is completed the button will disappear:

> 1. Round duration button: should be the date of duration of the whole round - set start date / end date and submit 
> 2. Set consideration phase button: a short period of time within the round duration to consider the proposal -set start date / end date and submit  
> 3. Set deliberation phase button: a short period of time within the round duration to deliberate about the considered proposal -set start date / end date and submit  - set start date / end date and submit 
> 4. Set voting phase button: a short period of time within the round duration to vote the approved proposals - set start date / end date and submit 
> 5. a confirmation of successful creation should be shown

KO
If I don't set the right data format it will show an error
if I dismiss the message without finishing the info I will lose the round creation without any warning message 

-
**Note: in the actual development there is no option to edit round data in the founding round channel or remove round in any channel. We need this options so I am adding 2 more scenarios:
-

**Scenario 9.1:  Edit funding round**

**Entry points:** 

1. Admin channel modify funding round button (option available in channel)
2. funding round channel, edit existing funding round button (option to be added in the other channel)

**User story**
As an Admin
I want to edit a funding round
So that it can be edited, reviewed and activated for funding proposals.

**Acceptance criteria:**
Given a valid funding round topic
When I execute the edit funding round button,  a drop down list is activated to select the round
Then the funding round modal details can be edited

**> Modal details:**
> Funding round name
> Description
> Budget
> Voting Address
> Voting Open Until 

and then Edit round duration, Edit consideration phase, Edit deliberation phase, Edit voting phase buttons are activated, and all the data can be edited. Once you complete the data of each option/button the button will disappear:

> 1. Round duration button:  edit start date / end date and submit 
> 2. Set consideration phase button: edit start date / end date and submit  
> 3. Set deliberation phase button: edit start date / end date and submit 
> 4. Set voting phase button: edit start date / end date and submit 
> 5. a confirmation of successful creation should be shown

If I don't set the right data format it will show an error
If I dismiss the message without finishing the info I will lose the round edition  

-

**Scenario 9.2: Remove funding round**

**Entry points:** 
1. Admin channel remove funding round button (to be created)
2. funding round channel, remove funding round button (to be created)

**User story**
As an Admin
I want to remove a funding round
So that it cannot be edited, reviewed and activated for funding proposals

**Acceptance criteria:**
Given a valid funding round topic
When I execute the remove funding round button,  a drop down list is activated to select the round
Then the funding round can be removed, a confirmation button and messages are provided

user type: Admin/ authorized reviewer - admin channel and funding round init discord channel

**NOTE: Phases of the funding rounds should be time framed in epochs**  https://towerstake.com/mina-time-machine/

**Comment by iluxonchik** [comment]
Hello. The editing of the Funding Round is included here: 
<img width="731" alt="fr" src="https://github.com/user-attachments/assets/0ef3690a-5bcd-426a-beb6-be66099cca91">

This is in the #admin channel. I can move it to another one if needed.

**Comment by CristinaEche** [comment]
@iluxonchik 
Can we add the same button allowing the user that has access to foundin.round init channel to only edit the rounds he created?  and the main button in the admin channel could provide editing to all admins. What do you think?

**Comment by CristinaEche** [comment]
@iluxonchik @es92 @remigiusz-antczak about Voting Address when creating a funding round: 

Is this a mina wallet address? web site? how can we confirm is a valid address? tks!

**Comment by remigiusz-antczak** [comment]
Scenario 9: Create funding round: set round duration, set consideration phase, set deliberation phase, set voting phase 

I successfully created a new funding round and set dates for each phase. I then tried to put the wrong date, which caused a correct error. I then canceled the round's creation, and it didn't show any error, which is correct. 

Proof:

https://github.com/user-attachments/assets/31cc29f4-c3e9-4dcf-ae13-1772f2748236


Scenario 9.1: Edit funding round 
**_Currently tested from the #admin channel; would be good to have this functionality also in the #funding-round-init in case someone created a funding round with a typo or wrong dates and wants to quickly adjust_**

I successfully edited all fields of a funding round with a correct success message. I then tried to put the wrong date, which caused a correct error. I then canceled the round's creation, and it didn't show any error, which is correct. 

Proof:


https://github.com/user-attachments/assets/8eb75def-80c8-491d-903c-474bc80675fa


Comments:
1. After editing the basic info of the funding round, the success message is shown without a button to return to edit the funding round. This button is present when changing round's dates: 
  - <img width="515" alt="image" src="https://github.com/user-attachments/assets/37cc392d-e962-4aab-a198-79f683925d19">
  - Please consider adding the same button after successfully editing the basic info. 
2. Please consider adding edit button in the #funding-round-init; currently this function is only accessible from the #admin channel.
3. This is more of a question than a comment, but I wanted to understand how the phases and dates work. Is it only informative to anyone who sees it, or does this also affect the Status of a funding round? I'm asking because I noticed all funding rounds are in VOTING status, which I understand is the voting to approve/reject the funding round, not the voting that happens on-chain with the community. 

Scenario 9.2: Remove funding round
**_Currently tested from the #admin channel; there's only option to REJECT a funding round, not REMOVE it_**

I successfully managed to reject (not remove) a funding round.

Proof:


https://github.com/user-attachments/assets/9c49f9c0-e8cd-492d-8e2e-1ce4c007b843


Comment: 
1. This is more of a question than a comment, but are we missing this functionality now? I couldn't find a place to remove a funding round (not just reject it). If we're missing it, I think it should be only available in the #admin channel to clean up the list of unnecessary funding rounds. However, I'm happy to discuss whether this option should be also possible from the #funding-round-init
2. Unify colors - please review messages and buttons and unify their appearance. [It was mentioned in the other issue/scenario](https://github.com/MinaFoundation/PGT_govbot/issues/6), but it seems like in this section, it'd also be good to unify the appearance of the buttons. I'd suggest the following order: Blue buttons (for navigating through the menu and sub-categories); Green buttons (for actions resulting in executing a specific functionality, for example, showing a pop-up modal, editing parameters/dates, etc.); Red buttons (for actions resulting in removing or rejecting something, for example, removing members, etc.). And if any type of button is missing, just show the next available one.

**Comment by remigiusz-antczak** [comment]
> @iluxonchik @es92 @remigiusz-antczak about Voting Address when creating a funding round:
> 
> Is this a mina wallet address? web site? how can we confirm is a valid address? tks!

I don't understand why we need a wallet address here. We discussed having a similar approach as we do in the [OCV platform](https://github.com/MinaFoundation/mina-on-chain-voting), where users send a transaction to themselves and put their voting preference in the memo field of the transaction. I'm unsure if we lost this in the discussion, so happy to align on this together!

**Comment by CristinaEche** [comment]
@iluxonchik 

Here again we need an autofill since if the funding round name is not typed in the correct way it will not let the user 

<img width="502" alt="Screenshot 2024-08-12 at 10 15 34" src="https://github.com/user-attachments/assets/43f3abf5-0bc4-4a13-9ffd-db94c6a25b8c">

<img width="604" alt="Screenshot 2024-08-12 at 10 15 58" src="https://github.com/user-attachments/assets/9b6dc131-f599-4d36-9b52-60382ae417f1">

**Comment by CristinaEche** [comment]
Now I can create and set phases, also the process has been updated:

To create a Funding round, the Topic selection is from the dropdown list, it is not required to memorize the topic:


<img width="534" alt="image" src="https://github.com/user-attachments/assets/1843dda7-3fca-4b42-8f23-f81112e93b98">

Then the modal for creating the new funding round has easier data filling and no voting address is required here:

<img width="380" alt="image" src="https://github.com/user-attachments/assets/99b6f5a5-a36f-4daa-a983-6d6d7f4f8f44">

and you can set up the rest of the information about the funding round and even set up the forum channel where the proposals related to the funding round will be posted 

<img width="571" alt="image" src="https://github.com/user-attachments/assets/ab9f5865-8e3b-45f3-8912-df273ee27641">


Color unification and button names will be done later, I will add another issue updating that info.
