### ISSUE TITLE
Scenario 11-11.1: Submit proposal to a funding round  / Scenario 11.2: Manage submitted proposals

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#15]
**Scenario 11: Submit proposal to a funding round** 

**Entry points:** propose channel, submit proposal to a funding round, drop down list

**User Story**
As a Community member
I want to Submit a proposal to a funding round
So that it can be considered for funding

Make sure the  proposal is complete with all the requested info is updated

**Acceptance criteria**
OK
Given that I executed the Submit proposal to a Funding Round button, selected a proposal and selected funding round name 
When I execute the Confirm Submission button 
Then The proposal should be added to the funding round successfully

KO
Given  that I have no draft proposals in my list 
When I use the Submit Proposal button
Then The system should return an error message indicating the failure to add the proposal to the funding round

-

**Scenario 11.1: Submit proposal to a funding round from manage drafts option** 

**Entry points:** propose channel, manage drafts, drop down list 

**User Story**
As a Community member
I want to submit a recently created proposal to a funding round
So that it can be considered for funding.

**Acceptance criteria**
Given A selected proposal from the list,
When I execute the button submit to funding round,
Then I have to select the funding round and click on the confirm submission button, my proposal should be submitted successfully and a confirmation message will be shown 

KO
only if the proposal cannot be added for any unknown reason

-

**Scenario 11.2: Manage submitted proposals** 

Entry points: propose channel, Manage my proposals, & drop down list, or from a recently added proposal & drop down list

**User Story**
As a Community member
I want to cancel a submitted proposal 
So that its removed from the funding round

Please notice that submitted proposals cannot be Edited.

**Acceptance criteria**
Given that I clicked on the Manage Proposal button, selected funding round and selected proposal from the list 
When I execute the button Cancel Proposal,
Then a Confirm Cancellation button is presented, I can cancel or go back. 
If Go back or dismiss message proposals are not canceled. 
If  Confirm cancellation the proposal is canceled and removed from the funding round, a successful confirmation message is presented

User type: Community member submitting the proposal - proposal channel

**Comment by remigiusz-antczak** [comment]
Scenario 11: Submit a proposal to a funding round

KO
Given that I have no draft proposals in my list
When I use the Submit Proposal button
Then, The system should return an error message indicating the failure to add the proposal to the funding round

I tried to submit a proposal to a funding round, but I don't have any proposals drafted yet, and I received a correct response:
` ℹ️ You have no draft proposals to submit.`

<img width="1051" alt="image" src="https://github.com/user-attachments/assets/a2ac86d8-58f0-4d21-ab34-7dc8594133f6">

**Comment by remigiusz-antczak** [comment]
Scenario 11.0.5 (?) (I think we're missing this scenario): Create a new proposal, edit, remove
Entry points: propose channel, manage drafts, drop-down list

**Edit: This is actually already covered in https://github.com/MinaFoundation/PGT_govbot/issues/12**

User Story 1
As a Community member
I want to create a proposal (that I could later submit to a funding round)
So that it can be considered for funding.

Acceptance criteria
OK
Given that I executed the Create New Proposal button, I must provide the required details (PROPOSAL NAME, BUDGET, and URL)
When I execute the Submit button
Then, the proposal should be created successfully

KO
if I dismiss the pop-up modal without providing the required details, I will lose the proposal creation without any warning message


User Story 2
As a Community member
I want to edit created proposals 
So that I can adjust it to increase my chances of getting funding.

Acceptance criteria
OK
Given that I executed the Manage Drafts button and selected a proposal from the drop-down list
When proposal details are presented, I can click on the Edit Proposal button
Then, I can adjust the proposal in a pop-up modal, click the Submit button, and successfully update the proposal.

KO
if I dismiss the pop-up modal without providing the required details, I will lose the proposal creation without any warning message

User Story 3
As a Community member
I want to remove created proposals
So that I can delete the ones I no longer need. 

Acceptance criteria
OK
Given that I executed the Manage Drafts button and selected a proposal from the drop-down list
When proposal details are presented, I can click on the Delete Proposal button
Then, I can click the Confirm Delete button and successfully remove the proposal

KO
if I click the Cancel button, I will be redirected to a previous view without any warning message


I successfully executed all the above scenarios in one video. Everything works correctly.

Proof:

https://github.com/user-attachments/assets/b732e862-5f89-4720-a860-45d5589571d3


Comments:
1. I suggest updating the user after editing a proposal. The proposal view is not updated (after editing it), and the user is required to open it again. But the user doesn't know about it because there's no update or notification. Please verify if this can be improved to make sure users understand.

**Comment by remigiusz-antczak** [comment]
Scenario 11.1: Submit proposal to a funding round from manage drafts option

Entry points: propose channel, manage drafts, drop down list

User Story
As a Community member
I want to submit a recently created proposal to a funding round
So that it can be considered for funding.

Acceptance criteria
Given A selected proposal from the list,
When I execute the button submit to funding round,
Then I have to select the funding round and click on the confirm submission button, my proposal should be submitted successfully and a confirmation message will be shown

KO
only if the proposal cannot be added for any unknown reason


I successfully managed to submit a proposal to a funding round (also reviewed cancelling options and they work correctly, too, more details in the proof video):
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/e9441387-da81-45c8-8614-c34a57a23020">

Proof:


https://github.com/user-attachments/assets/b1ae491b-5137-4442-b938-53bf28f38ce2

**Comment by remigiusz-antczak** [comment]
Scenario 11.2: Manage submitted proposals

Entry points: propose channel, Manage my proposals, & drop-down list, or from a recently added proposal & drop-down list

User Story
As a Community member
I want to cancel a submitted proposal
So that it's removed from the funding round

Please note that submitted proposals cannot be edited.

Acceptance criteria
Given that I clicked on the Manage Proposal button, selected funding round and selected proposal from the list
When I execute the button Cancel Proposal,
Then a Confirm Cancellation button is presented, I can cancel or go back.
If Go back or dismiss message proposals are not canceled.
If Confirm cancellation the proposal is canceled and removed from the funding round, a successful confirmation message is presented

User type: Community member submitting the proposal - proposal channel

I successfully managed to cancel a proposal:
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/91341b1d-1e41-4c0b-8e37-2fb063e3176e">


Proof:


https://github.com/user-attachments/assets/fd34074f-3c7d-49c3-b83d-b72d5f356237


Comments:
1. Unify Cancel buttons - When clicking the Cancel button while canceling a proposal, I'm not redirected to the previous view. Instead, an error message is displayed. Please review if we could unify how Cancel buttons behave across the whole platform to keep it consistent and avoid confusing people. More details are available in the Proof video above.
   - <img width="1021" alt="image" src="https://github.com/user-attachments/assets/f5864c6f-1788-423f-98ae-5302cc3ffef7">
2. Remove the Cancel My Proposal button when the proposal has already been canceled —When canceling a proposal, users can go back to their proposals and see the canceled one with an inactive button to cancel it. Since it's already been canceled, please review whether we can hide this button to avoid confusing users.
   - <img width="877" alt="image" src="https://github.com/user-attachments/assets/555210a3-1c8a-4a47-a1d9-1d5872980cd7">

**Comment by CristinaEche** [comment]
@iluxonchik 
We have the latest deployment on discord (Released Aug, 6th 11pm CET).

In the proposal section, in the main buttons, can you please organize the order of the the buttons and rename them: 

<img width="804" alt="image" src="https://github.com/user-attachments/assets/c71c0fbc-8ca9-4014-9ce3-7e735a81eca2">

Organize and rename them like this:

1- Create Proposal Draft
2- Manage Drafts
3- Submit Proposal
4- Manage Proposals

In the Proposal Management description please update to:

Proposal Management
Welcome to the Proposal Management channel. Here you can: create a proposal draft, manage the drafts, submit proposals to funding rounds and manage the submitted proposals.

**Comment by CristinaEche** [comment]
Tested the scenarios with community people:

A proposal if deleted from the forum cannot be canceled from user action to withdraw the proposal from the funding round.

Will add this to the list of bugs in another Issue.
