### ISSUE TITLE
Scenario 3 :  Remove reviewers / Scenario 3.1: Remove Groups 

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#7]
**Scenario 3:**

**Entry point:** Drop down list from the manage reviewers groups message

**User story**
As a system administrator
I want to remove a reviewer from a category/group
So that I can keep the reviewer categories up to date

**Acceptance criteria**
OK:
Given a valid group, select the desired group from the dropdown list
When the remove member button is executed
Then the select from the drop down list the specified member to be removed from the category, a confirmation message will be shown

KO:
Given an invalid username
When the remove member button is executed
Then the system returns an error message indicating the issue

-
**Scenario 3.1:** 

**Entry point:** Drop down list from Reviewers management button

**User story**
As a system administrator
I want to remove a reviewer group
So that I can keep the categories up to date

**Acceptance criteria**
OK:
Given a valid group, select the desired group from the dropdown list
When the remove reviewer group button is executed
Then the specified group is removed from the category list, a removal confirmation button will be shown 

-
**User type:** Admin / admin discord channel

**Comment by remigiusz-antczak** [comment]
Scenario 3 : Remove reviewers
(Scenario 3.1: Remove Groups is covered in a separate message below)

I removed a member from a group called "reviewers-group" and received a confirmation:
`Successfully removed 1 member(s) from the group.`
<img width="510" alt="image" src="https://github.com/user-attachments/assets/f866cd96-640d-40a1-9276-8f87277cc22f">

Then, I tried to remove the same user from a group called "reviewers-group", and I received a correct notification:
`Successfully removed 0 member(s) from the group.`
<img width="520" alt="image" src="https://github.com/user-attachments/assets/1e8c56c9-daef-458a-a864-0a1dc5ebf9ff">

Then, I tried to remove the same user plus a new one (a member of the group) from the group called "reviewers-group", and I received a correct notification:
`Successfully removed 1 member(s) from the group.`
<img width="513" alt="image" src="https://github.com/user-attachments/assets/96709316-ee40-46c0-896f-22769c6c3bbc">

Then, I tried to remove two existing members from the group called "reviewers-group", and I received a correct notification:
`Successfully removed 2 member(s) from the group.`
<img width="524" alt="image" src="https://github.com/user-attachments/assets/567c5611-7442-40d3-bc57-c77643fd5a76">

Then, when the group had 0 members, I tried to click on the `Remove Member` and received a correct notification:
`This group has no members to remove.`
<img width="503" alt="image" src="https://github.com/user-attachments/assets/974c739d-942e-41e9-ae90-07b7fc4dbea7">

Then, I quickly added a new member and tried to remove another user (who isn't a member of the group) from the group called "reviewers-group", and I received a correct notification:
`Successfully removed 0 member(s) from the group.`
<img width="527" alt="image" src="https://github.com/user-attachments/assets/26928f93-c96a-400c-966f-bd2f281cb45f">

Proof:
https://github.com/user-attachments/assets/454c2f2d-629e-4569-b1ef-ea06b22fe6f3

Comments:
1. Adjust the dropdown - [when adding new members to the group](https://github.com/MinaFoundation/PGT_govbot/issues/6), the dropdown where I could select them shows all channel members where the command is executed, which is correct behavior. However, when wanting to remove members, the dropdown again shows all channel members, not only the group members. Hence, it isn't easy to understand who is already a member and who should be removed. Please review if it's possible to show only group members when removing them from the group.
2. Unify error messages - sometimes, the error message shows in the main response window (for example, `Successfully removed 0 member(s) from the group.`), and sometimes, as a separate message (for example, `This group has no members to remove.`). Please review if we could unify the structure of such messages because it might confuse users, especially since some of these errors don't show too many details for users to understand what happened (for example, `This group has no members to remove.` is sent as a separate message, so it might be difficult for a user to understand which group is this referring to and what to do next, since this error message doesn't have any action button. Also, on the screenshot below, you can also see that when a user receives the separate error message, the previous one (in the previous message) wasn't removed, so now, the user sees two error messages in different places which might cause additional confusion.
<img width="529" alt="image" src="https://github.com/user-attachments/assets/17fc08ff-768b-4a88-8e78-fbdd86ecf587">

**Comment by remigiusz-antczak** [comment]
Scenario 3.1: Remove Groups
(Scenario 3 : Remove reviewers is covered in a separate message above)

I removed a group called "reviewers-group-2" and received a confirmation:
`SME Group has been successfully removed along with all its dependencies.`
<img width="496" alt="image" src="https://github.com/user-attachments/assets/4fd6a26e-ff09-41ce-a248-dfab27a73bb5">

Proof:
https://github.com/user-attachments/assets/1f3412c6-2199-40bf-be28-6d4f33ed2f8d

**Comment by iluxonchik** [comment]
ACK, thank you. Regarding the error messages, wrote on discord.

**Comment by CristinaEche** [comment]
@iluxonchik 

when removing members is there an option to inform the members that are already in the group? with something like a green tick or any other indication that the member is on the group so I know I can remove it easily?

In this example I am the only member but I am not sure if is ok, since there is no indication of that:

<img width="556" alt="image" src="https://github.com/user-attachments/assets/7d72f4ba-4665-41f6-807f-5b71d351ec16">

<img width="556" alt="image" src="https://github.com/user-attachments/assets/0012c05d-3323-4254-b9e9-248f7a167618">
