### ISSUE TITLE
Scenario 4 topic management:  Add topic - Scenario 4.1: Edit Topic 

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbot#8]
**Scenario 4:** 

**Entry point:** Topic management button from admin channel

**User Story**
As an admin
I want to add a new proposal topic
So that users can submit proposals under relevant topics

**Acceptance criteria**
OK
Given a valid topic name and topic details (link to MIP or MinaResearch as data support)
When the topic management button is executed
Then the add new topic button is activated and executed, a new proposal topic is created

KO
Given an invalid, missing or duplicate topic name
When the add new topic button is executed
Then the system returns an error message indicating the issue

-
**Scenario 4.1:** 

**Entry point:** Topic management button from admin channel, select topic from drop down list and edit button

**User Story**
As an admin
I want to edit a topic
So that users can submit proposals under relevant topics

**Acceptance criteria**
OK
Given a valid topic name selected from the list
When the Edit topic button is executed
Then the topic modal is shown and able to be edited
OK
Given a duplicate topic name or no changes
When the Edit topic button is executed and the modal edited
Then the system returns a message indicating the update (no errors are considered at this point)

-

**User type:** Admin / Admin discord channel

**Comment by remigiusz-antczak** [comment]
Scenario 4:

I created a topic called "topic1" and received a confirmation:
`✅ Topic 'topic1' created successfully`
<img width="424" alt="image" src="https://github.com/user-attachments/assets/7616a981-ef09-4b21-b490-31deaf5b515f">

I then tried to create another topic called "topic1" and received an error:
`🚫 An error occurred while creating the topic 'topic1': Validation error`
<img width="675" alt="image" src="https://github.com/user-attachments/assets/63a84095-ec14-4bae-9507-389d50d40e7e">

Proof:
https://github.com/user-attachments/assets/9701bf9d-a7b8-4150-a50a-2ae25d2dd20b

Comments:
1. Unify error messages - (it's also mentioned in the [other scenario](https://github.com/MinaFoundation/PGT_govbot/issues/7)) Please review if we could unify the structure of error messages because it might confuse users, especially since some of these errors don't show too many details for users to understand what happened
<img width="682" alt="image" src="https://github.com/user-attachments/assets/49b2b8a9-7d42-42cd-ad09-abfe712ac4fb">

**Comment by remigiusz-antczak** [comment]
Scenario 4.1:

I tried to edit a topic called "topic1" and received a confirmation unrelated to whether I changed something or not in the edit pop-up modal (which is a correct behavior):
`✅ Topic 'topic1' updated successfully`

<img width="445" alt="image" src="https://github.com/user-attachments/assets/927bb6d3-097c-4c4f-bb55-e6327478f28e">

Proof:
https://github.com/user-attachments/assets/0268581b-33fe-4609-b36b-e2992d18db83

**Comment by iluxonchik** [comment]
ACK, thank you. Also wrote on Discord.

**Comment by CristinaEche** [comment]
@iluxonchik 

In the create a Discussion Topic flow, can you please rename the button and update description to:

<img width="556" alt="image" src="https://github.com/user-attachments/assets/d4eb0dad-5b55-4fd0-b02c-6f5f0120a45e">

- Add Discussion Topic

- Manage Discussion Topics
Select a Discussion Topic from the list or add a new one. (Page 1/1)

**Comment by CristinaEche** [comment]
@iluxonchik 

Rename button to : Edit Discussion topic

<img width="556" alt="image" src="https://github.com/user-attachments/assets/cba089d2-93ac-425f-9ae6-ce34e1ee993f">
